### ISSUE TITLE
SBF GPS Support

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/GpsDrivers#42] opened 2019-06-05 07:07 UTC
Hi @MatejFranceskin thanks for implementing the SBF driver. I wanted to check with you on recent updates from your end since I'd have some small changes I could push.

1) Enable "Support" log on Rover and Base by default, handy when analyzing GPS precision

2) Divide h- and v-accuracy by 2 because they report 2DRMS, otherwise it seems the EPH/EPV values are not comparable with what we get from uBlox for example.

Thoughts?

Plus I could add a PR for supporting it on the PX4 side.

**Comment by MatejFranceskin** [comment] 2019-06-05 07:14
Sounds great!
I suggest that you first submit PR for GpsDrivers and after it is reviewed and merged you go for PX4 side. Note that same GpsDrivers module is used in PX4 Firmware and QGC for base station support.

**Comment by AndreasAntener** [comment] 2019-06-05 08:12
Right. Why was the SBF support not added yet to PX4, just lack of testing or did you still see issues?

**Comment by MatejFranceskin** [comment] 2019-06-05 08:26
I thought it was added to PX4, now I see that changes to gps.cpp didn't go in. It was tested with the AsteRx-m2 on the UAV and base station on QGC. I will check what happened with the merge. The problem is that currently I don't have the hardware to test it.

**Comment by AndreasAntener** [comment] 2019-06-05 08:27
Ok, I did do that change on my end so I could also add a PR for that later.

**Comment by MatejFranceskin** [comment] 2019-06-05 08:32
My changes are stuck in pr-septentrio branch. As I don't have the hardware now, it would be really great if you test it and create a new PR.

**Closed** 2019-06-05 14:43 UTC
